### ISSUE TITLE
In the lab website there is no admin to change pages or add sections.

### ISSUE THREAD

**Issue by Garyfallidis** [Garyfallidis/lab#3]
:100:

**Comment by ghoshbishakh** [comment]
Yes actually I have not put any link in the navbar to the admin page. http://elef.soic.indiana.edu/lab/dashboard/login?next=/lab/dashboard/

**Comment by skoudoro** [comment]
How can I add a small "Log in" button on the top right ?

**Comment by ghoshbishakh** [comment]
So we can just add a link to the dashboard view in https://github.com/Garyfallidis/lab/blob/master/website/templates/website/header.html#L31

**Comment by ghoshbishakh** [comment]
`<li><a href="{% url "dashboard_login" %}">Login</a></li>`
