### ISSUE TITLE
Research section issues

### ISSUE THREAD

**Issue by Garyfallidis** [Garyfallidis/lab#31]
1. Cannot add a new section.
2. Markdown is not enabled.
3. Update Research Section. Will send a google doc.
4. All images are here https://github.com/Garyfallidis/garyfallidis.github.com/tree/master/images

**Comment by skoudoro** [comment]
1 - 2 - 3 is fixed on #34 !

**Comment by skoudoro** [comment]
everything is done on this isssue. Closing !
